name: menu-service CI -> DockerHub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Lấy code từ repo về máy runner
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Cài Python để chạy pytest
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Cài dependencies + chạy test integration menu_service
      - name: Install deps and run tests (menu_service)
        working-directory: menu_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx
          PYTHONPATH=. pytest -q

      # 4) Login DockerHub (dùng secrets)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5) Build image từ Dockerfile trong menu_service
      - name: Build docker image
        run: |
          docker build ./menu_service -t ${{ secrets.DOCKER_USERNAME }}/menu-service:latest

      # 6) Push image lên DockerHub
      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/menu-service:latest

